Safe_Require("config.ui")
Safe_Require("config.editor-basic")
Safe_Require("config.lsp-relative")
Safe_Require("config.builtin")
Safe_Require("config.git")
vim.cmd("so /home/sanae/.config/nvim/lua/config/lsp-relative/dap1/dap2.lua")
vim.cmd("colorscheme vaporwave")
