Safe_Require("lspkind").init({

	mode = "symbol_text",
	preset = "default",
	symbol_map = {
		Text = "󰦨",
		Method = "",
		Class = "",
		Function = "󰊕",
		Constructor = "󱃤",
		Field = "",
		Variable = "",
		Interface = "",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Constant = "",
		Keyword = "󰻾",
		Enum = "Ⓔ",
		Struct = "Ⓢ",
		Color = "",
		EnumMember = "󰕋",
		Event = "",
		File = "",
		Folder = "",
		Operator = "",
		Reference = "",
		Snippet = "",
		TypeParameter = "",
	},
})
