Safe_Require("config.ui.theme")
Safe_Require("config.ui.highlight")
Safe_Require("config.ui.whichkey")
Safe_Require("config.ui.diagnostic")
Safe_Require("config.ui.lsp")
Safe_Require("config.ui.opacity")
Safe_Require("config.ui.notify1")
Safe_Require("config.ui.image2")
