vim.lsp.enable("lua_ls")
vim.lsp.enable("json_ls")
vim.lsp.enable("marksman")
vim.lsp.enable("lemminx")
vim.lsp.enable("cmake")
vim.lsp.enable("taplo")
vim.lsp.enable("bash")
-- vim.lsp.enable("omnisharp")
vim.lsp.enable("pyright")
-- vim.lsp.enable("roslyn_ls")
