vim.keymap.set("n", "<leader>fb", function()
	Snacks.picker.buffers()
end, { desc = "Buffers", silent = true })
vim.keymap.set("n", "<leader>ff", function()
	Snacks.picker.smart()
end, { desc = "smart find files", silent = true })
vim.keymap.set("n", "<leader>fp", function()
	Snacks.picker.projects()
end, { desc = "projects", silent = true })
vim.keymap.set("n", "<leader>fr", function()
	Snacks.picker.recent()
end, { desc = "recent files", silent = true })
vim.keymap.set("n", "<leader>uC", function()
	Snacks.picker.colorschemes()
end, { desc = "colorschemes", silent = true })
vim.keymap.set("n", "<leader>hh", function()
	Snacks.picker.help()
end, { desc = "helps", silent = true })
vim.keymap.set("n", "<leader>fg", function()
	Snacks.picker.grep()
end, { desc = "greps file", silent = true })
vim.keymap.set("n", "<leader>sM", function()
	Snacks.picker.man()
end, { silent = true, desc = "Mans" })
vim.keymap.set("n", "gd", function()
	Snacks.picker.lsp_definitions()
end, { silent = true, desc = "definitions" })
vim.keymap.set("n", "gD", function()
	Snacks.picker.lsp_declarations()
end, { silent = true, desc = "definitions" })
vim.keymap.set("n", "gr", function()
	Snacks.picker.lsp_references()
end, { silent = true, desc = "references" })
vim.keymap.set("n", "<leader>fs", function()
	Snacks.picker.lsp_symbols()
end, { silent = true, desc = "symbols" })
vim.keymap.set("n", "<leader>fw", function()
	Snacks.picker.lsp_workspace_symbols()
end, { silent = true, desc = "workspace symbols" })
vim.keymap.set("n", "<leader>lg", function()
	Snacks.lazygit()
end, { silent = true, desc = "lazygit" })
vim.keymap.set("n", "<leader>ssi", function()
	Snacks.picker.icons()
end, { desc = "icons search" })
vim.keymap.set("n", "<leader>ssk", function()
	Snacks.picker.keymaps()
end, { desc = "keymaps search" })
vim.keymap.set("n", "<leader>ssk", function()
	Snacks.picker.keymaps()
end, { desc = "keymaps search" })
vim.keymap.set("n", "<leader>ssh", function()
	Snacks.picker.highlights()
end, { desc = "highlights search" })
vim.keymap.set("n", "<leader>gb", function()
	---@type snacks.terminal.Opts
	local opts = {}
	Snacks.git.blame_line(opts)
end)
vim.keymap.set({ "n", "t" }, "<c-/>", function()
	---@type snacks.terminal.Opts
	local opts = {}
	opts.win = { max_height = 25, position = "bottom", border = "rounded" }
	Snacks.terminal.toggle("zsh", opts)
end)
vim.keymap.set("n", "<leader>nt", "<cmd>NoiceSnacks<cr>", { desc = "noice snacks" })
