vim.keymap.set("n", "<leader>fb", function()
	Snacks.picker.buffers()
end, { desc = "Buffers", silent = true })
vim.keymap.set("n", "<leader>ff", function()
	Snacks.picker.smart()
end, { desc = "smart find files", silent = true })
vim.keymap.set("n", "<leader>fp", function()
	Snacks.picker.projects()
end, { desc = "projects", silent = true })
vim.keymap.set("n", "<leader>fr", function()
	Snacks.picker.recent()
end, { desc = "recent files", silent = true })
vim.keymap.set("n", "<leader>uC", function()
	Snacks.picker.colorschemes()
end, { desc = "colorschemes", silent = true })
vim.keymap.set("n", "<leader>hh", function()
	Snacks.picker.help()
end, { desc = "helps", silent = true })
vim.keymap.set("n", "<leader>fg", function()
	Snacks.picker.grep()
end, { desc = "greps file", silent = true })
vim.keymap.set("n", "<leader>sM", function()
	Snacks.picker.man()
end, { silent = true, desc = "Mans" })
vim.keymap.set("n", "gd", function()
	Snacks.picker.lsp_definitions()
end, { silent = true, desc = "definitions" })
vim.keymap.set("n", "gD", function()
	Snacks.picker.lsp_declarations()
end, { silent = true, desc = "definitions" })
vim.keymap.set("n", "gr", function()
	Snacks.picker.lsp_references()
end, { silent = true, desc = "references" })
vim.keymap.set("n", "<leader>fs", function()
	Snacks.picker.lsp_symbols()
end, { silent = true, desc = "symbols" })
vim.keymap.set("n", "<leader>fw", function()
	Snacks.picker.lsp_workspace_symbols()
end, { silent = true, desc = "workspace symbols" })
vim.keymap.set("n", "<leader>lg", function()
	Snacks.lazygit()
end, { silent = true, desc = "lazygit" })
